apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: 'marutidock/flask_gcp'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      
